package org.eclipse.scout.scout.shared.table;

import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.page.AbstractTablePageData;

import javax.annotation.Generated;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "org.eclipse.scout.scout.client.table.TableTablePage", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class TableTablePageData extends AbstractTablePageData {
    private static final long serialVersionUID = 1L;

    @Override
    public TableTableRowData addRow() {
        return (TableTableRowData) super.addRow();
    }

    @Override
    public TableTableRowData addRow(int rowState) {
        return (TableTableRowData) super.addRow(rowState);
    }

    @Override
    public TableTableRowData createRow() {
        return new TableTableRowData();
    }

    @Override
    public Class<? extends AbstractTableRowData> getRowType() {
        return TableTableRowData.class;
    }

    @Override
    public TableTableRowData[] getRows() {
        return (TableTableRowData[]) super.getRows();
    }

    @Override
    public TableTableRowData rowAt(int index) {
        return (TableTableRowData) super.rowAt(index);
    }

    public void setRows(TableTableRowData[] rows) {
        super.setRows(rows);
    }

    public static class TableTableRowData extends AbstractTableRowData {
        private static final long serialVersionUID = 1L;
        public static final String idNr = "idNr";
        public static final String name = "name";
        public static final String surname = "surname";
        public static final String age = "age";
        private Long m_idNr;
        private String m_name;
        private String m_surname;
        private Long m_age;

        public Long getIdNr() {
            return m_idNr;
        }

        public void setIdNr(Long newIdNr) {
            m_idNr = newIdNr;
        }

        public String getName() {
            return m_name;
        }

        public void setName(String newName) {
            m_name = newName;
        }

        public String getSurname() {
            return m_surname;
        }

        public void setSurname(String newSurname) {
            m_surname = newSurname;
        }

        public Long getAge() {
            return m_age;
        }

        public void setAge(Long newAge) {
            m_age = newAge;
        }
    }
}
